### ISSUE TITLE
HDR BC6 formats can't be opened.

### ISSUE THREAD

**Issue by RokkuDayo** [Nenkai/ForzaDecryptor#3]
Skydomes from Forza Motorsport 5 are stored as Unsigned BC6H textures as per their asset manifest but the TexConv tool fails to convert them.

What I presume are their mipmaps, which for some reason are stored separatedly, do produce an output but they can't be opened in any software. Oddly enough, hovering over these broken DDS files in Blender with a DDS Importer plugin show a very small preview of them despite not being openable.

![image](https://github.com/user-attachments/assets/ecd4aade-1d6e-4fec-9476-579b8a101898)

Sample: https://mega.nz/file/hW4iDIDL#Kbxfp6yV5DKig56usj31bNgT8pjs7rDaINEvuVW4M6o

**Comment by Nenkai** [comment]
Try again with 1.0.1.

I should have fixed the issue, but the lowest mip file doesn't quite convert properly still. No clue how to solve.

**Comment by RokkuDayo** [comment]
Worked like a charm. Thanks a bunch.
